# Generated by Django 4.1.3 on 2022-12-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_user_alter_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
