# Generated by Django 4.1.4 on 2022-12-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_user_alter_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='start_price',
        ),
    ]
