# Generated by Django 4.1.4 on 2022-12-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_price_listings_start_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_bids', to='auctions.listings'),
            preserve_default=False,
        ),
    ]
