# Generated by Django 4.1.4 on 2022-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category_remove_listings_user_listings_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
