# Generated by Django 4.1.4 on 2022-12-12 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listings_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='item',
        ),
        migrations.AddField(
            model_name='listings',
            name='current_bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bid', to='auctions.bids'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
