# Generated by Django 4.1.4 on 2022-12-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listings_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bid', to='auctions.bids'),
        ),
    ]
