# Generated by Django 4.1.4 on 2022-12-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_bids_bid_alter_listings_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='isActive',
            field=models.BooleanField(),
        ),
    ]
