# Generated by Django 4.1.4 on 2022-12-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_listings_listed_by_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='watchlist',
        ),
    ]
