# Generated by Django 4.1.4 on 2022-12-18 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_listings_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='userwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
